name: deploy bot

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: update version
      run: ssh ${{ secrets.MIKRUS_CONNECTION_STRING }} -i <(echo ${{ secrets.SSH_KEY }}) sh -c "echo TAG=${{ github.ref_name }} > role_bot.env; sudo systemctl restart bot"
